use_frameworks!

platform :ios, '10.0'

target 'SwiftBankLoanModule_Example' do
  pod 'SwiftBankLoanModule', :path => '../'

  target 'SwiftBankLoanModule_Tests' do
    inherit! :search_paths

    
  end
end
